version: "3.3"

# NOTE: If using Docker, ensure there's no .env file in the root directory. If one exists, rename it. 
# Docker Compose might conflict with NextJs 13.4.19's .env format.

# This should be the same as below if you are running via docker compose up
x-webapp-url: &webapp_url http://formbricks:3000

# PostgreSQL DB for Formbricks to connect to
x-database-url: &database_url "postgresql://postgres:postgres@postgres:5432/formbricks?schema=public"

# NextJS Auth
# @see: https://next-auth.js.org/configuration/options#nextauth_secret
# You can use: `openssl rand -base64 32` to generate one
x-nextauth-secret: &nextauth_secret RANDOM_STRING

# Set this to your public-facing URL, e.g., https://example.com
# You do not need the NEXTAUTH_URL environment variable in Vercel.
x-nextauth-url: &nextauth_url http://localhost:3000

# Set it to true to enable a dedicated connection pool for Prisma using Prisma Data Proxy
# Cold boots will be faster and you'll be able to scale your DB independently of your app.
# @see https://www.prisma.io/docs/data-platform/data-proxy/use-data-proxy
x-prisma-generate-data-proxy: &prisma_generate_data_proxy

# Necessary if email verification and password reset are enabled.
# See further below if you want to disable these features.
x-mail-from: &mail_from
x-smtp-host: &smtp_host
x-smtp-port: &smtp_port
# Enable SMTP_SECURE_ENABLED for TLS (port 465)
x-smtp-secure-enabled: &smtp_secure_enabled
x-smtp-user: &smtp_user
x-smtp-password: &smtp_password

# Set the below two values to your public-facing URL, e.g., https://example.com
x-next-public-webapp-url: &next_public_webapp_url http://localhost:3000
x-next-public-survey-base-url: &next_public_survey_base_url http://localhost:3000/s

# Set the below values to display privacy policy, imprint and terms of service links in the footer of signup & public pages.
x-next-public-privacy-url: &next_public_privacy_url
x-next-public-terms-url: &next_public_terms_url
x-next-public-imprint-url: &next_public_imprint_url

# Email Verification. If you enable Email Verification you have to setup SMTP-Settings, too.
x-next-public-email-verification-disabled: &next_public_email_verification_disabled 1

# Password Reset. If you enable Password Reset functionality you have to setup SMTP-Settings, too.
x-next-public-password-reset-disabled: &next_public_password_reset_disabled 1

# Signup. Disable the ability for new users to create an account.
x-next-public-signup-disabled: &next_public_signup_disabled 0

# Team Invite. Disable the ability for invited users to create an account.
x-next-public-invite-disabled: &next_public_invite_disabled 0

# Disable Sentry warning
x-sentry-ignore-api-resolution-error: &sentry_ignore_api_resolution_error

# Enable Sentry Error Tracking
x-next-public-sentry-dsn: &next_public_sentry_dsn

# Configure Github Login
x-next-public-github-auth-enabled: &next_public_github_auth_enabled 0
x-github-id: &github_id
x-github-secret: &github_secret

# Configure Google Login
x-next-public-google-auth-enabled: &next_public_google_auth_enabled 0
x-google-client-id: &google_client_id
x-google-client-secret: &google_client_secret

# Cron Secret
x-cron-secret: &cron_secret

services:
  postgres:
    restart: always
    image: postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  formbricks:
    restart: always
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        NEXT_PUBLIC_WEBAPP_URL: *next_public_webapp_url
        NEXT_PUBLIC_SURVEY_BASE_URL: *next_public_survey_base_url
        NEXT_PUBLIC_PRIVACY_URL: *next_public_privacy_url
        NEXT_PUBLIC_TERMS_URL: *next_public_terms_url
        NEXT_PUBLIC_IMPRINT_URL: *next_public_imprint_url
        NEXT_PUBLIC_EMAIL_VERIFICATION_DISABLED: *next_public_email_verification_disabled
        NEXT_PUBLIC_PASSWORD_RESET_DISABLED: *next_public_password_reset_disabled
        NEXT_PUBLIC_SIGNUP_DISABLED: *next_public_signup_disabled
        NEXT_PUBLIC_INVITE_DISABLED: *next_public_invite_disabled
        SENTRY_IGNORE_API_RESOLUTION_ERROR: *sentry_ignore_api_resolution_error
        NEXT_PUBLIC_SENTRY_DSN: *next_public_sentry_dsn
        NEXT_PUBLIC_GITHUB_AUTH_ENABLED: *next_public_github_auth_enabled
        GITHUB_ID: *github_id
        GITHUB_SECRET: *github_secret
        NEXT_PUBLIC_GOOGLE_AUTH_ENABLED: *next_public_google_auth_enabled
        GOOGLE_CLIENT_ID: *google_client_id
        GOOGLE_CLIENT_SECRET: *google_client_secret
        CRON_SECRET: *cron_secret
        WEBAPP_URL: *webapp_url
        DATABASE_URL: *database_url
        NEXTAUTH_SECRET: *nextauth_secret
        NEXTAUTH_URL: *nextauth_url

    depends_on:
      - postgres
    ports:
      - 3000:3000

    environment:
      WEBAPP_URL: *webapp_url
      DATABASE_URL: *database_url
      NEXTAUTH_SECRET: *nextauth_secret
      NEXTAUTH_URL: *nextauth_url
      PRISMA_GENERATE_DATAPROXY: *prisma_generate_data_proxy
      MAIL_FROM: *mail_from
      SMTP_HOST: *smtp_host
      SMTP_PORT: *smtp_port
      SMTP_SECURE_ENABLED: *smtp_secure_enabled
      SMTP_USER: *smtp_user
      SMTP_PASSWORD: *smtp_password

volumes:
  postgres:
    driver: local
