version: "3.3"
x-environment: &environment
  environment:
    ########################################################################
    # ------------ MANDATORY (CHANGE ACCORDING TO YOUR SETUP) ------------#
    ########################################################################

    # PostgreSQL DB for Formbricks to connect to
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/formbricks?schema=public"

    # Uncomment to enable a dedicated connection pool for Prisma using Prisma Data Proxy
    # Cold boots will be faster and you'll be able to scale your DB independently of your app.
    # @see https://www.prisma.io/docs/data-platform/data-proxy/use-data-proxy
    # PRISMA_GENERATE_DATAPROXY=true
    PRISMA_GENERATE_DATAPROXY:

    # NextJS Auth
    # @see: https://next-auth.js.org/configuration/options#nextauth_secret
    # You can use: `openssl rand -base64 32` to generate one
    NEXTAUTH_SECRET: RANDOM_STRING
    # Set this to your public-facing URL, e.g., https://example.com
    # You do not need the NEXTAUTH_URL environment variable in Vercel.
    NEXTAUTH_URL: http://localhost:3000

services:
  postgres:
    restart: always
    image: postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  formbricks:
    restart: always
    image: formbricks/formbricks:latest
    depends_on:
      - postgres
    ports:
      - 3000:3000
    <<: *environment

volumes:
  postgres:
    driver: local
