{{- if .Values.hub.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "formbricks.hubname" . }}
  labels:
    helm.sh/chart: {{ include "formbricks.chart" . }}
    app.kubernetes.io/name: {{ include "formbricks.hubname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: hub
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ .Values.partOfOverride | default (include "formbricks.name" .) }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "formbricks.hubname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
{{- end }}
